[package]
name = "problem-template"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[dev-dependencies]
pretty_assertions = "1.2.1"
rstest = "0.14.0"
rstest_reuse = "0.3.0"
